modify the grub.cfg in centos

diff --git a/roles/installer/files/fetch_target b/roles/installer/files/fetch_target
--- a/roles/installer/files/fetch_target
+++ b/roles/installer/files/fetch_target
@@ -15,8 +15,8 @@ if [ $? -eq 0 ]; then
       umount /dev/sda2
       mount "/dev/sda2" "/mnt/sda2"
       if [ ! $? -eq 0 ];then
-	 echo "unable to mount /dev/sda2. quitting"
-	 exit 1
+      	 echo "unable to mount /dev/sda2. quitting"
+	       exit 1
       fi
       SOURCEMNT="/mnt/sda2"
       LIBRARYMNT="/mnt/sda3"
@@ -124,6 +124,12 @@ done
 # get the md5 of mydata
 #	
 md5sum /mnt/sdb2/tce/mydata.tgz > /mnt/sdb2/tce/mydata.tgz.md5.txt
+
+# get the OS version
+cd ${SOURCEMNT}/boot/
+KENREL_VERSION=`ls | grep vmlinuz-3 | head -n 1`
+echo "KERNEL_VERSION=${KERNEL_VERSION}" >> /mnt/sdb2/tce/installer.conf
+
 cp ${SOURCEMNT}/root/anaconda-ks.cfg /mnt/sdb2/tce/
 cp ${SOURCEMNT}/boot/efi/EFI/fedora/grub.cfg /mnt/sdb2/tce/grub.cfg.efi
 cp ${SOURCEMNT}/boot/grub/grub.cfg /mnt/sdb2/tce/grub.cfg.mbr
